### ISSUE TITLE
Dashboard Controller Duplication Issue

### ISSUE THREAD

**Issue by tcavaletto** [Team-Delta/GitMyCurriculum#142]
https://codeclimate.com/github/Team-Delta/GitMyCurriculum/DashboardController

**Comment by ChristianMurphy** [comment]
Could be resolved by combining
line 41

``` ruby
 @created_curricula.each do |c|
```

and line 51

``` ruby
@contributed_curricula.each do |c|
```

into something like

``` ruby
@all_curricula_involved = @created_curricula + @contributed_curricula
@all_curricula_involved.each do |c|
```

**Comment by ChristianMurphy** [comment]
same would apply for line 20 and 27

**Comment by bammons** [comment]
I have already tried this and it doesn't work. If you've tried it and seen otherwise, let me know
