### ISSUE TITLE
Notification for removing contributor

### ISSUE THREAD

**Issue by bammons** [Team-Delta/GitMyCurriculum#231]
When a contributor is removed there should be a notification

**Comment by tcavaletto** [comment]
I'm thinking maybe skip that notification, for a similar reason as Facebook
having notifications for adding friends but not for removing them.

On Apr 24, 2014, at 10:41 AM, Bailey Ammons notifications@github.com
wrote:

When a contributor is removed there should be a notification

—
Reply to this email directly or view it on
GitHubhttps://github.com/Team-Delta/GitMyCurriculum/issues/231
.

**Comment by tcavaletto** [comment]
Gosh dang it email.

**Comment by bammons** [comment]
Sounds good. I'll just close it then
